.TH "SecPlus::Auth" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::Auth \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinitSession\fP ($name= 'secplus_auth_session')"
.br
.ti -1c
.RI "static \fBaddSession\fP ($namevalue=array())"
.br
.ti -1c
.RI "static \fBhasSession\fP ($name)"
.br
.ti -1c
.RI "static \fBdestroySession\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 823 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "static addSession ($namevalue = \fCarray()\fP)\fC [static]\fP"
.PP
Definition at line 833 of file secplus.lib.php.
.SS "static destroySession ()\fC [static]\fP"
.PP
Definition at line 843 of file secplus.lib.php.
.SS "static hasSession ($name)\fC [static]\fP"
.PP
Definition at line 839 of file secplus.lib.php.
.SS "static initSession ($name = \fC'secplus_auth_session'\fP)\fC [static]\fP"
.PP
Definition at line 824 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
