.TH "SecPlus::IController" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::IController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAbstractController\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetup\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for controllers 
.PP
Definition at line 294 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "setup ()"\fBSecPlus\fP automatically call this method for set up the controller 

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
