.TH "SecPlus::IShellCommand" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::IShellCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBShellCmd\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhelp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 849 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "help ()"
.PP
Implemented in \fBHelpCommand\fP, \fBCreateCommand\fP, and \fBExitCommand\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
