.TH "SecPlus::AbstractValueObject" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::AbstractValueObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIValueObject\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__set\fP ($name, $val)"
.br
.ti -1c
.RI "\fB__get\fP ($name)"
.br
.ti -1c
.RI "\fB__isset\fP ($name)"
.br
.ti -1c
.RI "\fB__unset\fP ($name)"
.br
.ti -1c
.RI "\fB__call\fP ($func, $args)"
.br
.ti -1c
.RI "\fBgetData\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$_data\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 565 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "__call ($func, $args)"
.PP
Definition at line 588 of file secplus.lib.php.
.SS "__get ($name)"
.PP
Definition at line 572 of file secplus.lib.php.
.SS "__isset ($name)"
.PP
Definition at line 580 of file secplus.lib.php.
.SS "__set ($name, $val)"
.PP
Definition at line 568 of file secplus.lib.php.
.SS "__unset ($name)"
.PP
Definition at line 584 of file secplus.lib.php.
.SS "getData ()"
.PP
Definition at line 603 of file secplus.lib.php.
.SH "Field Documentation"
.PP 
.SS "$_data = array()\fC [protected]\fP"
.PP
Definition at line 566 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
