.TH "SecPlus::Create" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::Create \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIShellCommand\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($config, $project_dir)"
.br
.ti -1c
.RI "\fBhelp\fP ()"
.br
.ti -1c
.RI "\fBdao\fP ($name, $tableName)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$config\fP"
.br
.ti -1c
.RI "\fB$project_dir\fP"
.br
.ti -1c
.RI "\fB$abstractModelClass\fP = 'SecPlus\\\fBAbstractModel\fP'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 642 of file secplus.lib.php.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($config, $project_dir)"
.PP
Definition at line 647 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "dao ($name, $tableName)"
.PP
Definition at line 664 of file secplus.lib.php.
.SS "help ()"
.PP
Implements \fBIShellCommand\fP.
.PP
Definition at line 652 of file secplus.lib.php.
.SH "Field Documentation"
.PP 
.SS "$abstractModelClass = 'SecPlus\\\fBAbstractModel\fP'\fC [protected]\fP"
.PP
Definition at line 645 of file secplus.lib.php.
.SS "$config\fC [protected]\fP"
.PP
Definition at line 643 of file secplus.lib.php.
.SS "$project_dir\fC [protected]\fP"
.PP
Definition at line 644 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
