.TH "SecPlus::SQLBuilder" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::SQLBuilder \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBupdate\fP ($table_name, $values, $where=NULL)"
.br
.ti -1c
.RI "static \fBinsert\fP ($table_name, $values, $primary_key= 'id')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 657 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "static insert ($table_name, $values, $primary_key = \fC'id'\fP)\fC [static]\fP"
.PP
Definition at line 686 of file secplus.lib.php.
.SS "static update ($table_name, $values, $where = \fCNULL\fP)\fC [static]\fP"
.PP
Definition at line 658 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
