.TH "SecPlus::IModel" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::IModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAbstractModel\fP.
.SH "Detailed Description"
.PP 
Interface to Models 
.PP
Definition at line 557 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
