.TH "SecPlus::WebFramework" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::WebFramework \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($conf)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBhandleController\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$config\fP"
.br
.ti -1c
.RI "\fB$controller\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main class 
.PP
Definition at line 230 of file secplus.lib.php.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($conf)"
.PP
Definition at line 235 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "handleController ()\fC [protected]\fP"Controller manager. Identify the controller and execute. 
.PP
Definition at line 273 of file secplus.lib.php.
.SH "Field Documentation"
.PP 
.SS "$config\fC [protected]\fP"
.PP
Definition at line 232 of file secplus.lib.php.
.SS "$controller\fC [protected]\fP"
.PP
Definition at line 233 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
