.TH "SecPlus::Database" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::Database \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetConnection\fP ()"
.br
.ti -1c
.RI "static \fBcloseConnection\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manages the database 
.PP
Definition at line 611 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "static closeConnection ()\fC [static]\fP"
.PP
Definition at line 652 of file secplus.lib.php.
.SS "static getConnection ()\fC [static]\fP"Connect to database 
.PP
Definition at line 623 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
