.TH "SecPlus" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.ti -1c
.RI "class \fBWebFramework\fP"
.br
.ti -1c
.RI "interface \fBIController\fP"
.br
.ti -1c
.RI "class \fBAbstractController\fP"
.br
.ti -1c
.RI "class \fBAbstractModel\fP"
.br
.ti -1c
.RI "interface \fBIModel\fP"
.br
.ti -1c
.RI "interface \fBIValueObject\fP"
.br
.ti -1c
.RI "class \fBAbstractValueObject\fP"
.br
.ti -1c
.RI "class \fBDatabase\fP"
.br
.ti -1c
.RI "class \fBSQLBuilder\fP"
.br
.ti -1c
.RI "class \fBUtil\fP"
.br
.ti -1c
.RI "class \fBHelper\fP"
.br
.ti -1c
.RI "interface \fBIAuthController\fP"
.br
.ti -1c
.RI "class \fBAbstractAuthController\fP"
.br
.ti -1c
.RI "class \fBAuth\fP"
.br
.ti -1c
.RI "interface \fBIShellCommand\fP"
.br
.ti -1c
.RI "class \fBShellCmd\fP"
.br
.ti -1c
.RI "class \fBHelpCommand\fP"
.br
.ti -1c
.RI "class \fBCreateCommand\fP"
.br
.ti -1c
.RI "class \fBExitCommand\fP"
.br
.ti -1c
.RI "class \fBShell\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "if(php_sapi_name()=='cli') \fBsecplus_cmd\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "if (php_sapi_name()=='cli') SecPlus::secplus_cmd ()"
.PP
Definition at line 1275 of file secplus.lib.php.
.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
