.TH "SecPlus::IValueObject" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::IValueObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAbstractValueObject\fP.
.SH "Detailed Description"
.PP 
Definition at line 561 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
