.TH "SecPlus::HelpCommand" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::HelpCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShellCmd\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauto\fP ()"
.br
.ti -1c
.RI "\fBhelp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 885 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "auto ()"
.PP
Definition at line 886 of file secplus.lib.php.
.SS "help ()"
.PP
Implements \fBIShellCommand\fP.
.PP
Definition at line 899 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
