.TH "SecPlus::AbstractAuthController" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::AbstractAuthController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractController\fP, and \fBIAuthController\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcheckPermissions\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$session\fP"
.br
.ti -1c
.RI "\fB$token\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 805 of file secplus.lib.php.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
.PP
Definition at line 811 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "checkPermissions ()\fC [protected]\fP"
.PP
Definition at line 816 of file secplus.lib.php.
.SH "Field Documentation"
.PP 
.SS "$session\fC [protected]\fP"
.PP
Definition at line 808 of file secplus.lib.php.
.SS "$token = array()\fC [protected]\fP"
.PP
Definition at line 809 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
