.TH "secplus" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secplus \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBsecplus.lib.php\fP
.PP
SEC+ WebFramework License: GNU GPL v2.0 Light MVC PHP Framework designed for security.
.PP
\fBAuthor:\fP
.RS 4
i4k - Tiago Natel de Moura <tiago4orion@gmail.com> 
.PP
m0nad - Victor Ramos Mello <victornrm@gmail.com>
.RE
.PP
\fBVersion:\fP
.RS 4
1.0 -php 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
