.TH "SecPlus::Util" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::Util \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBerror_security\fP ($text, $inc_html_header=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 728 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "static error_security ($text, $inc_html_header = \fCtrue\fP)\fC [static]\fP"
.PP
Definition at line 729 of file secplus.lib.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
