.TH "SecPlus::IAuthController" 3 "Sat Jul 21 2012" "Version 1.0" "SecPlus-PHP Web Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecPlus::IAuthController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAbstractAuthController\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpermissionDenied\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 801 of file secplus.lib.php.
.SH "Member Function Documentation"
.PP 
.SS "permissionDenied ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for SecPlus-PHP Web Framework from the source code.
