<?php

/**
 * Generated by SecPlus-PHP WebFramework
 * http://github.com/SecPlus/secplus-php
 *
 * http://www.secplus.com.br/
 */

if ($_SERVER['SCRIPT_FILENAME'] == __FILE__) {
  print ";)";
  die();
 }

class Config extends SecPlus\Config {

  const PROJECT_NAME = "";
  
  protected function __construct() {
    parent::__construct();
    $this->setUp();
  }

  private function setUp() {

    $this->setEnvironment(SecPlus\Config::ENV_DEVELOPMENT);

    /**
     * Every developer file need to be included in this array.
     * This is a extra security against malicious file include.
     */
    $this->safeFiles = array(
                             /* Controllers */
                             $this->controllerDir . '/HomeController.php',

                             /* DAO */

                             /* View */
                             $this->viewDir . '/HomeView.php'
                             );

    $this->debug = true;

    $this->dbHost = '127.0.0.1';
    $this->dbUser = 'user';
    $this->dbPass = '';
    $this->dbDatabase = '';
  }
}
