<!--

Generated by SecPlus-PHP MVC WebFramework
Author: Tiago Natel de Moura

See: http://github.com/SecPlus/secplus-php
Page: {#view_name#}
-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?php print $title; ?></title>

</head>

<body>

<?php /* include("header.php"); */ ?>
<?php /* include("menu.php"); */ ?>

<!-- Content of your website -->

View generated by SecPlus-PHP.

<?php /* include("body.php"); */ ?>


<?php /* include("footer.php"); */ ?>

</body>
</html>
